### ISSUE TITLE
System is not anonymyous

### ISSUE THREAD

**Issue by kitswas** [OSDG-IIITH/Review-IIIT#13]
The current system is using a hash as the key for the Reviews in the DB. 
https://github.com/OSDG-IIITH/Review-IIIT/blob/794da2bebfebb3bc3ec1237c2177f5649d68404e/backend/routes/members.py#L79
The hash is generated from the user's name, email and rollno.
https://github.com/OSDG-IIITH/Review-IIIT/blob/794da2bebfebb3bc3ec1237c2177f5649d68404e/backend/routes/members.py#L93

A hostile actor could theoretically get a list of all student emails, roll numbers and names and hash them (brute force) to ID the reviewers.  
It's **game-over** if someone gets access to the database storing the reviews. 

A better way would be to issue a persistent token to each student, which is used to post reviews.
It's the students' responsibility to store the token safely. 
In one DB, we can store whether a student has been issued a token, but not the token itself. 
Generated tokens go into a lookup table. (To check whether a user token exists or not)
Tokens can be generated using hash + random salt or UUIDs.

The _only_ trade-off is that once the token is lost, the user cannot reset, and they cannot use the platform again.
That's the price of **complete anonymity**.

**Comment by ankith26** [comment]
> A hostile actor could theoretically get a list of all student emails, roll numbers and names and hash them (brute force) to ID the reviewers.

While this is definitely possible, the underlying assumption made here is that it is very difficult/time-consuming and therefore very unlikely that someone is going to try to do it. An attacker must
a. Get a list of all emails, roll numbers and most importantly, names as stored in CAS attributes. Unless one has CAS backend access, I believe it unlikely to get the name to match exactly with all the casing and word combinations.
b. Get access to the database itself (as you pointed out). The backend never exposes the hashes at all to the user side in any public facing API, the only way to even begin brute forcing is to get database access, and as a maintainer I take all precautions to the best of my skill to ensure that the database is secure.

Therefore, given the practicalities, I consider the system to be anonymous. Your proposed solution, while great from a technical standpoint, is not as user friendly as the current system. We can't expect all users to properly keep track of their tokens and not loose it, out of the 100s of users, someone or the other is bound to forget or misplace it.

**Comment by kitswas** [comment]
@ankith26 
You overlooked one scenario.
What if the institution forces you to hand-over control?
Can OSDG still ensure anonymity of the users?

This system is not completely anonymyous by design. That's the point I wanted you to note.
I thought of this only after a few students expressed concerns over anonymity.

**Comment by ankith26** [comment]
> What if the institution forces you to hand-over control?

1. They are not law enforcement, they have no right to do it.
2. We are not doing anything even remotely illegal to even be worried about it.

I suppose the "forces hand" argument can apply to any other social media (say, whatsapp) used by students to discuss the same details that would be discussed on this portal, yet I have never heard any case of the institute forcing anyone to reveal their whatsapp chats or whatever on this matter, as that would be plain privacy invasion.

Anyways, I think a github issue is not the best place to continue this discussion, but if you want to continue this conversation or have any other concerns/queries I would love to address this further on any other media, starting with email (feel free to email us at the OSDG email)
